language: cpp
compiler: gcc
sudo: true
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - libgtest-dev
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev valgrind cmake qt5-default
script:
  - export CC=gcc-8
  - export CXX=g++-8
  - mkdir build
  - cd build
  - cmake  ..
  - cmake --build .